### ISSUE TITLE
AttributeError: TNscan instance has no attribute 'portScanner'

### ISSUE THREAD

**Issue by spythedude** [x3omdax/PenBox#13]
Hi X3, great tool, mate - I'm just having a play about but seem to have an issue here..  

4) Find control panel
 5) Find zip files
 6) Find upload files
 7) Get server users
 8) Scan from SQL injection
 9) Scan ports (range of ports)
 10) Scan ports (common ports)
 11) Get server banner
 12) Bypass Cloudflare
 99) Exit

 Enter choice -> 9
 Enter range of ports, (ex : 1-1000) -> 21-443
Traceback (most recent call last):
  File "penbox.py", line 1477, in <module>
    menu()
  File "penbox.py", line 87, in menu
    info()
  File "penbox.py", line 638, in info
    menu()
  File "penbox.py", line 93, in menu
    exp()
  File "penbox.py", line 734, in exp
    menu()
  File "penbox.py", line 97, in menu
    webhack()
  File "penbox.py", line 322, in webhack
    menu()
  File "penbox.py", line 97, in menu
    webhack()
  File "penbox.py", line 322, in webhack
    menu()
  File "penbox.py", line 97, in menu
    webhack()
  File "penbox.py", line 322, in webhack
    menu()
  File "penbox.py", line 99, in menu
    tnn()
  File "penbox.py", line 1299, in **init**
    TNscan(aaa)
  File "penbox.py", line 824, in **init**
    self.portScanner(1, ran)
AttributeError: TNscan instance has no attribute 'portScanner'

**Comment by x3omdax** [comment]
will fix soon

**Comment by x3omdax** [comment]
works just fine here http://pix.toile-libre.org/upload/original/1471982907.png try to install any dependencies or lybraries that you dont have

**Comment by spythedude** [comment]
Options 9 and 10 in Private Tools are no good 

![image](https://cloud.githubusercontent.com/assets/6370247/17908210/6cd30a92-6977-11e6-8bd9-ace139834e27.png)

**Comment by x3omdax** [comment]
https://github.com/x3omdax/PenBox/commit/1b170d8cfc0f23fa6f94877ed8b99e3d1bc42a7b

**Comment by spythedude** [comment]
still same bro..  When I run the original TNscan it works perfectly

![image](https://cloud.githubusercontent.com/assets/6370247/17911180/2c95877c-6984-11e6-9260-b9e420e7d15a.png)

**Comment by x3omdax** [comment]
did you add spaces +    def portScanner(self, mode, ran) : ??
